#!/usr/bin/python3

# -*- coding: utf-8 -*-
import sys
import ngsolve.gui as G


if __name__ == "__main__":
    gui = G.GUI()
    del G
    if len(sys.argv) > 1:
        gui.run(sys.argv[1])
    else:
        gui.run()

