#!/usr/bin/python3

# -*- coding: utf-8 -*-
import sys, os
import ngsolve.gui as G
import ngsolve as ngs
import netgen.meshing

def Draw(obj, *args, tab=None, **kwargs):
    """Draw a Mesh or a CoefficientFunction, this function is overridden by
    the new gui and returns the drawn scene."""
    scene = None
    for _type, creator in G.GUI.sceneCreators:
        if isinstance(obj,_type):
            scene = creator(obj, *args, **kwargs)
            break
    if scene:
        G.gui.draw(scene, tab=tab)
        return scene
    print("Cannot draw object of type ",type(obj))

def Redraw(blocking=True,**kwargs):
    if blocking:
        G.gui.redraw_blocking()
    else:
        G.gui.redraw()

if __name__ == "__main__":
    ngs.Draw = Draw
    ngs.Redraw = Redraw
    G.gui = G.GUI()
    def do_after_run():
        for option in sys.argv[1:]:
            if os.path.isfile(option):
                name,ext = os.path.splitext(option)
                if ext == ".py":
                    G.gui.loadPythonFile(option)
                    file_loaded = True
                else:
                    G.gui.msgbox = QtWidgets.QMessageBox(text = "Cannot load file type: " + ext)
                    G.gui.msgbox.setWindowTitle("File loading error")
                    G.gui.msgbox.show()
    G.gui.parseFlags(sys.argv[1:])
    G.gui.run(do_after_run)
